### ISSUE TITLE
Runtime.Exec raises TypeError: Object doesn't support this property or method on Windows System

### ISSUE THREAD

**Issue by Dinuz** [sstephenson/execjs#176] opened 2015-01-20 00:15 UTC
I am using a gem called autoprefixer-rails that use the execjs gem.
The gem works fine on unix systems (with node.js), but raises a specific error on windows systems (the error is related with the runtime.exec).

The following screenshot is the result of the test suit:

![auto](https://cloud.githubusercontent.com/assets/1139472/5810119/0df19fee-a00f-11e4-9301-77249b0763c4.jpg)

The issue comes from the following piece of code:

    def process(css, opts = {})
       opts = convert_options(opts)

       result = runtime.exec(
          "processor = autoprefixer(#{ js_params(opts[:from]) });" +
          "return eval(process.apply(this, #{::JSON.generate([css,opts])}));")

        Result.new(result['css'], result['map'])
    end

Specifically the line:

    result = runtime.exec(
          "processor = autoprefixer(#{ js_params(opts[:from]) });" +
          "return eval(process.apply(this, #{::JSON.generate([css,opts])}));") 

The runtime.exec has something wrong inside, but for the life of me I cannot figure out what.

Could someone helps us in figuring out what and where the issue is? In this way we can change the gem in order to be OS platform independent?

Thanks in advance

Dinuz and @ai

**Comment by ai** [comment] 2015-01-20 11:32
@josh there are many bug reports in AutoprefixerRails with different source and error message from ExecJS.

**Comment by josh** [comment] 2015-01-20 19:30
A few things that could help here.

* Test on both node.js and jscript runnings on windows. Its possible one or the other works and one is broken. That might at least isolate the problem further. You can force a specific runtime with `EXECJS_RUNTIME=JScript ruby test-whatever.rb`
* See if theres any ES5 features being used in autoprefixer. In the JScript case, you can only hope for ES3 support. Node should run most ES5 features.
* Try the latest execjs. execjs 2.2.2 has a number of Windows 8 specific JScript fixes.
* See if you can create a minimal ruby script test suite that loads the autoprefixer source and reproduces the bug.

**Comment by Dinuz** [comment] 2015-01-20 19:34
With node there is no issue!

**Comment by josh** [comment] 2015-01-20 19:42
> With node there is no issue!

I meant node on windows.

**Comment by Dinuz** [comment] 2015-01-20 20:05
Going to install it and let you know

**Comment by ai** [comment] 2015-01-20 21:34
@josh yeap, some of ES5 features really used in Autoprefixer.

How I can check in Autoprefixer, that it is Windows and ExecJS uses `JScript`?

**Comment by josh** [comment] 2015-01-20 21:47
I'd probably recommend some sort of feature detection based on the functions you're expecting. I'm not sure what those are, but lets say for example you need `Function.prototype.bind`.

`ExecJS.eval "typeof Function.prototype.bind === 'function'"` would tell you if the feature was supported. I wouldn't recommend hard coding any OS or versions since Windows 9 (or whatever) might upgrade JScript with support or older Mac's might have crappy versions of `JSC`.

You might also be able to use an ES5 shim library you could load in if you really needed those features.

**Comment by ai** [comment] 2015-01-20 21:48
@josh thanks, it is important notice. Shame on me, that I forget about it :).

**Comment by Dinuz** [comment] 2015-01-20 22:50
@josh

How I know which js engine is enable now?

I installed node, and obvy all the spec are passing:)

But I would love to know if node is enable as default js engine or not, and
eventually how switch back to jscript without uninstalling node.

Do you have idea?

**Comment by ai** [comment] 2015-01-20 22:56
@josh is `ENV['EXECJS_RUNTIME'] = 'Node'` a good way to force to use `node` in ExecJS on Windows? Or ExecJs will automatically find `node` if it is installed on Windows?

**Comment by josh** [comment] 2015-01-20 23:01
Node is always chosen if it's in the path on either OSX. I totally forget the correct way to configure Windows PATH :) but yeah if node.exe exists that should work

**Comment by Dinuz** [comment] 2015-01-20 23:01
@ai Honestly, after I installed node, seems that ExecJs automatically found
it....I didn't do absolutely nothing, and all the spec are now passing
(this means my system is using node as default js engine).
I wish to know how from cmd I can switch between node and jscript windows
as default engine (or if after I installed node, that automatically
replaced the default js engine for windows).

**Comment by ai** [comment] 2015-01-20 23:03
Thanks for help. I think we can close this issue. Most likly that problem was from ES3 JScript runtime. I will just ban it in AutoprefixerRails.

**Comment by Dinuz** [comment] 2015-01-20 23:05
@ai and @josh, just to recap, the bottom line of the problem is that
windows jscript engine is still on ES3, and in our case obviously using ES5
features would never work without an upgrading to node or V8?

If this is the case, @ai it's better putting this information in the
readme, and list as a warning, otherwise people can go crazy before
understanding what is going on.

@josh, is the case to add a little note about this type of things also on
the execjs page?

**Comment by ai** [comment] 2015-01-20 23:07
Yeap, I will add notice to README and add check with understandable error. So wwe can clos only ExecJS issue. AutoprefixerRails issue I will close after this fixes.

**Comment by Dinuz** [comment] 2015-01-20 23:08
@ai agree!

**Closed** 2015-01-20 23:17 UTC

**Comment by josh** [comment] 2015-01-21 00:25
Added a section to the readme about ES5 features 1816df22d1e18bd6c8150e007014207d7fa7a8c4
